In [39]:
import sympy as sp

# Define the variables
x, y = sp.symbols('x y')

# Define the equations
eq1 = sp.Eq(-0.37337867 * (y - x) + 86.31728176 + x, 604.068379)
eq2 = sp.Eq(-0.03802049 * (y - x) + 65.31942752 + x, 608.170719)

# Solve the system of equations
solution = sp.solve((eq1, eq2), (x, y))

# Display the solution
print("Solution:")
print(f"x = {solution[x]}")
print(f"y = {solution[y]}")


Solution:
x = 545.696970342224
y = 620.542898477927


In [85]:
import sympy as sp

# Define the variables
x, y = sp.symbols('x y')

# Define the equations
eq1 = sp.Eq(0.08665147 * (y - x) +57.55656327 + x, 609.9835)
eq2 = sp.Eq(-0.7999282* (y - x) + 113.8237938 + x, 597.2727)

# Solve the system of equations
solution = sp.solve((eq1, eq2), (x, y))

# Display the solution
print("Solution:")
print(f"x = {solution[x]}")
print(f"y = {solution[y]}")

Solution:
x = 545.685243969180
y = 623.487648946501


In [6]:
import numpy as np
f0 = 545.853023#float(solution[x])
f1 = 623.653411211#float(solution[y])
# Specify the path and filename
filename_an1 = 'an1.txt'
filename_an2 = 'an2.txt'
matrix =  np.array([[         np.nan, 457.74885809, 460.70069237, 463.65252665,
        466.60216223],
       [466.96523442, 469.92057413, 472.87591385, 475.83125357,
        478.78659329],
       [479.49650835, 482.45184807, 485.40592233, 488.35999659,
                 np.nan],
       [         np.nan,          np.nan, 531.90854739, 534.86038883,
        537.81045731],
       [         np.nan, 535.71541587, 538.66505145, 541.61468703,
        544.56432261],
       [539.37243953, 542.32856506, 545.282623  , 548.23445728,
        551.18629156],
       [545.79903465, 548.75437437, 551.70971409, 554.6650538 ,
                 np.nan],
       [551.93251007, 554.88784978, 557.8431895 ,          np.nan,
                 np.nan],
       [         np.nan,          np.nan,          np.nan, 593.57925724,
        596.52889282],
       [         np.nan,          np.nan, 594.63100532, 597.58214852,
        600.5317841 ],
       [         np.nan, 596.04519024, 598.9992645 , 601.95109877,
        604.90293305],
       [597.70461366, 600.65995337, 603.61408859, 606.56592286,
        609.51775714],
       [602.54187381, 605.49786766, 608.45194192, 611.40601618,
                 np.nan],
       [607.64452195, 610.59842172, 613.55249598,          np.nan,
                 np.nan],
       [613.1734413 , 616.12878102,          np.nan,          np.nan,
                 np.nan],
       [         np.nan,          np.nan,          np.nan,          np.nan,
        596.85291985],
       [         np.nan,          np.nan,          np.nan, 600.80649199,
        603.75612757],
       [         np.nan,          np.nan, 603.98153689, 606.63337117,
        609.58272399],
       [         np.nan, 606.05031215, 609.0043864 , 611.95622068,
        614.90805496],
       [608.02108391, 610.97515816, 613.92923242, 616.88150547,
        619.83099091],
       [612.56078504, 615.5148593 , 618.46893356, 621.42101298,
                 np.nan],
       [616.66311518, 619.6184549 , 622.57248451,          np.nan,
                 np.nan],
       [620.15168428, 623.107024  ,          np.nan,          np.nan,
                 np.nan],
       [620.45592666,          np.nan,          np.nan,          np.nan,
                 np.nan]])

# Read the text file and load the content into an array
matrix_an1 = read_mat(filename_an1)
matrix_an2 = read_mat(filename_an2)
# print(np.shape(matrix_an1),np.shape(matrix_an2))

print(matrix_an1)
print(matrix_an2)

# Print the array to verify its content

new_matrix = f0+matrix_an2+matrix_an1*(f1-f0)
# print(new_matrix)

differences = np.diff(new_matrix, axis=1)
#print(differences)
average_differences = np.nanmean(differences, axis=0)
# print(average_differences)
new_matrix[np.isnan(new_matrix)] = 0
def fill_zeros(row, spacings):
    zero_indices = np.where(row == 0)[0]
    non_zero_indices = np.where(row != 0)[0]
    
    if len(non_zero_indices) == 0:
        # If there are no non-zero elements, we cannot interpolate/extrapolate
        return row
    
    for i in range(len(row)):
        if row[i] == 0:
            # Find the nearest non-zero indices before and after the zero element
            prev_index = non_zero_indices[non_zero_indices < i][-1] if len(non_zero_indices[non_zero_indices < i]) > 0 else None
            next_index = non_zero_indices[non_zero_indices > i][0] if len(non_zero_indices[non_zero_indices > i]) > 0 else None
            
            if prev_index is not None and next_index is not None:
                # Interpolate
                row[i] = row[prev_index] + (row[next_index] - row[prev_index]) * (i - prev_index) / (next_index - prev_index)
            elif prev_index is not None:
                # Extrapolate backwards
                row[i] = row[prev_index] + spacings[prev_index] * (i - prev_index)
            elif next_index is not None:
                # Extrapolate forwards
                row[i] = row[next_index] - spacings[next_index - 1] * (next_index - i)
    
    return row
filled_matrix = np.zeros(np.shape(new_matrix))
for i, row in enumerate(new_matrix):
    filled_matrix[i] = fill_zeros(row, average_differences)
nan_positions = np.isnan(matrix)
filled_matrix[nan_positions] = np.nan
cali_freqs = filled_matrix
print(cali_freqs)

[[        nan -1.10604999 -0.90558319 -0.7054106  -0.50553126]
 [-0.49914448 -0.29838249 -0.09791569  0.1022569   0.30213624]
 [ 0.35522557  0.55598756  0.75645437  0.95662695         nan]
 [        nan         nan -0.93084378 -0.73067119 -0.53079185]
 [        nan -0.65893423 -0.45846742 -0.25829484 -0.0584155 ]
 [-0.40122879 -0.2004668  -0.          0.20017259  0.40005193]
 [ 0.03259571  0.2333577   0.4338245   0.63399708         nan]
 [ 0.4208005   0.62156249  0.8220293          nan         nan]
 [        nan         nan         nan -0.99912427 -0.79924492]
 [        nan         nan -0.91483058 -0.714658   -0.51477865]
 [        nan -0.81148413 -0.61101733 -0.41084474 -0.2109654 ]
 [-0.69732182 -0.49655983 -0.29609303 -0.09592045  0.10395889]
 [-0.37337867 -0.17261668  0.02785012  0.22802271         nan]
 [-0.03802049  0.1627415   0.36320831         nan         nan]
 [ 0.3203964   0.52115839         nan         nan         nan]
 [        nan         nan         nan         nan -0.79

In [4]:
import numpy as np

# Define the file path
file_path_an1 = 'an1.txt'  # Change this to your actual file path
file_path_an2 = 'an2.txt'
def read_mat(file_path):
    with open(file_path, 'r') as f:
        lines = f.readlines()
        data = []
        for line in lines:
            # Split the line by whitespace and convert to float, replacing 'NaN' with np.nan
            row = [float(x) if x.lower() != 'nan' else np.nan for x in line.split()]
            data.append(row)
    
    # Convert to NumPy array
    matrix = np.array(data)
    return matrix

print(read_mat(file_path_an1))


[[        nan -1.10604999 -0.90558319 -0.7054106  -0.50553126]
 [-0.49914448 -0.29838249 -0.09791569  0.1022569   0.30213624]
 [ 0.35522557  0.55598756  0.75645437  0.95662695         nan]
 [        nan         nan -0.93084378 -0.73067119 -0.53079185]
 [        nan -0.65893423 -0.45846742 -0.25829484 -0.0584155 ]
 [-0.40122879 -0.2004668  -0.          0.20017259  0.40005193]
 [ 0.03259571  0.2333577   0.4338245   0.63399708         nan]
 [ 0.4208005   0.62156249  0.8220293          nan         nan]
 [        nan         nan         nan -0.99912427 -0.79924492]
 [        nan         nan -0.91483058 -0.714658   -0.51477865]
 [        nan -0.81148413 -0.61101733 -0.41084474 -0.2109654 ]
 [-0.69732182 -0.49655983 -0.29609303 -0.09592045  0.10395889]
 [-0.37337867 -0.17261668  0.02785012  0.22802271         nan]
 [-0.03802049  0.1627415   0.36320831         nan         nan]
 [ 0.3203964   0.52115839         nan         nan         nan]
 [        nan         nan         nan         nan -0.79

In [60]:

x =''' 
  NaN  461.1632  463.5226  465.8805  468.2371
  468.5573  470.9181  473.2774  475.6354  477.9920
  478.5415  480.9022  483.2616  485.6195       NaN
       NaN       NaN  534.8060  537.1640  539.5206
       NaN  537.8010  540.1604  542.5184  544.8749
  540.7010  543.0617  545.4211  547.7790  550.1356
  545.8358  548.1965  550.5559  552.9138       NaN
  550.7968  553.1575  555.5169       NaN       NaN
       NaN       NaN       NaN  596.6939  599.0504
       NaN       NaN  597.5032  599.8612  602.2178
       NaN  598.6145  600.9738  603.3318  605.6884
  599.9344  602.2952  604.6545  607.0125  609.3691
  603.8072  606.1679  608.5273  610.8853       NaN
  607.9047  610.2654  612.6248       NaN       NaN
  612.3585  614.7193       NaN       NaN       NaN
       NaN       NaN       NaN       NaN  599.3738
       NaN       NaN       NaN  602.4922  604.8488
       NaN       NaN  604.7545  607.1125  609.4691
       NaN  606.6206  608.9800  611.3379  613.6945
  608.1778  610.5385  612.8978  615.2558  617.6124
  611.8002  614.1609  616.5203  618.8783       NaN
  615.0887  617.4494  619.8088       NaN       NaN
  617.9061  620.2668       NaN       NaN       NaN
  618.2116       NaN       NaN       NaN       NaN
  '''

print(x)

 
  NaN  461.1632  463.5226  465.8805  468.2371
  468.5573  470.9181  473.2774  475.6354  477.9920
  478.5415  480.9022  483.2616  485.6195       NaN
       NaN       NaN  534.8060  537.1640  539.5206
       NaN  537.8010  540.1604  542.5184  544.8749
  540.7010  543.0617  545.4211  547.7790  550.1356
  545.8358  548.1965  550.5559  552.9138       NaN
  550.7968  553.1575  555.5169       NaN       NaN
       NaN       NaN       NaN  596.6939  599.0504
       NaN       NaN  597.5032  599.8612  602.2178
       NaN  598.6145  600.9738  603.3318  605.6884
  599.9344  602.2952  604.6545  607.0125  609.3691
  603.8072  606.1679  608.5273  610.8853       NaN
  607.9047  610.2654  612.6248       NaN       NaN
  612.3585  614.7193       NaN       NaN       NaN
       NaN       NaN       NaN       NaN  599.3738
       NaN       NaN       NaN  602.4922  604.8488
       NaN       NaN  604.7545  607.1125  609.4691
       NaN  606.6206  608.9800  611.3379  613.6945
  608.1778  610.5385  612.8978  61